// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::*;
use time::OffsetDateTime;

use diesel::prelude::*;
use uuid::Uuid;
#[derive(diesel::Identifiable, diesel::Selectable, diesel::Queryable)]
#[diesel(table_name = users)]
pub struct User {
    pub id: Uuid,
    pub username: String,
    pub email: String,
    pub password: String,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}
